swagger: "2.0"
info:
  version: "1.0.0"
  title: "Todo list"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "todo"
schemes:
- "https"
- "http"
paths:
  /todos:
    post:
      tags:
      - "todo"
      summary: "Add a new todo"
      description: ""
      operationId: "addTodo"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Todo"
      responses:
        200:
          description: "successful operation - returns id"
          schema:
            $ref: "#/definitions/TodoSaved"
        400:
          description: "Invalid body"
    get:
      tags:
      - "todo"
      summary: "Get todos"
      operationId: "getTodos"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Todos"
  /todo/{todoId}:
    patch:
      tags:
      - "todo"
      summary: "Update an existing todo"
      description: ""
      operationId: "updateTodo"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Todo properties that need to be updated"
        required: true
        schema:
          $ref: "#/definitions/TodoPatch"
      - name: "todoId"
        in: "path"
        description: "Todo id to update"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "succesful operation"
        400:
          description: "Invalid ID supplied"
    delete:
      tags:
      - "todo"
      summary: "Deletes a todo"
      description: ""
      operationId: "deleteTodo"
      produces:
      - "application/json"
      parameters:
      - name: "todoId"
        in: "path"
        description: "Todo id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
definitions:
  Todo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        example: "Shopping list"
      text:
        type: "string"
        example: "<ul><li>Bread</li><li>Cheese</li></ul>"
        description: "Longtext - Not required"
      createdAt:
        type: "string"
        example: "26.07.2019"
      finished:
        type: "boolean"
        example: false
  TodoSaved:
    type: "integer"
    format: "int64"
    example: 1
  TodoPatch:
    type: "object"
    properties:
      finished:
        type: "boolean"
        example: true
  Todos:
    type: "array"
    xml:
      name: "todo"
      wrapped: true
    items:
      $ref: "#/definitions/Todo"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"